version: '3.9'

services:
  db:
    container_name: postgres_container
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ontibike
    ports:
      - 5432:5432
    volumes:
      - pgVolFinal:/var/lib/postgresql/data
      - ./db/init.dump:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - practica_net
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    container_name: pgadmin4_container_final
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadminFinal:/var/lib/pgadmin
    networks:
      - practica_net
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    networks:
      - practica_net
    restart: unless-stopped
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend_container
    ports:
      - 5173:5173
    command: npm run dev
    networks:
      - practica_net
  loadbalancer:
    image: nginx:latest
    container_name: nginx_loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    entrypoint: []
    networks:
      - practica_net
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    networks:
    - practica_net
    ports:
    - "9090:9090"
    volumes:
    - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - backend
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana_practica
    networks:
    - practica_net
    ports:
    - "3500:3000"
    volumes:
    - ./Grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    - myGrafanaVol:/var/lib/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: grafana-clock-panel 1.0.1
    depends_on:
    - prometheus


volumes:
  pgVolFinal: {}
  pgadminFinal: {}
  myGrafanaVol: 
networks:
  practica_net:
